# Generated by Django 5.1.3 on 2024-11-06 13:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('borrowed', 'borrowed'), ('lent', 'lent')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'active'), ('deleted', 'deleted'), ('waiting', 'waiting'), ('done', 'done')], max_length=50)),
                ('currence', models.CharField(choices=[('usd', 'usd'), ('uz', 'uz'), ('eur', 'eur'), ('rub', 'rub')], max_length=50)),
                ('whom', models.CharField(max_length=13)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('back_money', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrack',
                'verbose_name_plural': 'Contracks',
                'ordering': ['-id'],
            },
        ),
    ]
