# Generated by Django 5.1.3 on 2024-11-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrack', '0002_rename_contrack_contrackmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrackmodel',
            name='whom',
            field=models.CharField(max_length=20),
        ),
    ]
